namespace Aselia.Common.Flags
{
	public enum Modes : int
	{
		A = (int)'A',
		B = (int)'B',
		C = (int)'C',
		D = (int)'D',
		E = (int)'E',
		F = (int)'F',
		G = (int)'G',
		H = (int)'H',
		I = (int)'I',
		J = (int)'J',
		K = (int)'K',
		L = (int)'L',
		M = (int)'M',
		N = (int)'N',
		O = (int)'O',
		P = (int)'P',
		Q = (int)'Q',
		R = (int)'R',
		S = (int)'S',
		T = (int)'T',
		U = (int)'U',
		V = (int)'V',
		W = (int)'W',
		X = (int)'X',
		Y = (int)'Y',
		Z = (int)'Z',
		a = (int)'a',
		b = (int)'b',
		c = (int)'c',
		d = (int)'d',
		e = (int)'e',
		f = (int)'f',
		g = (int)'g',
		h = (int)'h',
		i = (int)'i',
		j = (int)'j',
		k = (int)'k',
		l = (int)'l',
		m = (int)'m',
		n = (int)'n',
		o = (int)'o',
		p = (int)'p',
		q = (int)'q',
		r = (int)'r',
		s = (int)'s',
		t = (int)'t',
		u = (int)'u',
		v = (int)'v',
		w = (int)'w',
		x = (int)'x',
		y = (int)'y',
		z = (int)'z',
		D0 = (int)'0',
		D1 = (int)'1',
		D2 = (int)'2',
		D3 = (int)'3',
		D4 = (int)'4',
		D5 = (int)'5',
		D6 = (int)'6',
		D7 = (int)'7',
		D8 = (int)'8',
		D9 = (int)'9',
	}
}